apiVersion: v1
kind: Service
metadata:
  name: wazuh-indexer-http
  namespace: wazuh
spec:
  type: ClusterIP
  selector:
    app: wazuh-indexer
  ports:
    - name: http
      port: 9200
      targetPort: 9200
