apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-indexer
  namespace: wazuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-indexer
  serviceName: wazuh-indexer
  template:
    metadata:
      labels:
        app: wazuh-indexer
      name: wazuh-indexer
    spec:
      securityContext:
        fsGroup: 1000
      volumes:
        - name: indexer-certs
          secret:
            secretName: indexer-certs
            defaultMode: 0600
      initContainers:
        - name: volume-mount-hack
          image: busybox
          command:
            - sh
            - -c
            - chown -R 1000:1000 /var/lib/wazuh-indexer
          volumeMounts:
            - name: wazuh-indexer
              mountPath: /var/lib/wazuh-indexer
        - name: increase-the-vm-max-map-count
          image: busybox
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
      containers:
        - name: wazuh-indexer
          image: wazuh/wazuh-indexer:4.7.3
          resources:
            limits:
              cpu: 500m
              memory: 1564Mi
          env:
            - name: bootstrap.memory_lock
              value: "false"
            - name: network.host
              value: "0.0.0.0"
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: cluster.initial_cluster_manager_nodes
              value: wazuh-indexer-0
            - name: discovery.seed_hosts
              value: "wazuh-indexer-0.wazuh-indexer"
            - name: node.max_local_storage_nodes
              value: "1"
            - name: plugins.security.allow_default_init_securityindex
              value: "true"
            - name: NODES_DN
              value: CN=indexer,OU=Wazuh,O=Wazuh,L=California,C=US
            - name: OPENSEARCH_JAVA_OPTS
              value: "-Xms1g -Xmx1g"
            - name: DISCOVERY_SERVICE
              value: wazuh-indexer
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: DISABLE_INSTALL_DEMO_CONFIG
              value: "true"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              add: ["SYS_CHROOT"]
          volumeMounts:
            - name: wazuh-indexer
              mountPath: /var/lib/wazuh-indexer
            - name: indexer-certs
              mountPath: /usr/share/wazuh-indexer/config/certs
              readOnly: true
          ports:
            - containerPort: 9200
              name: indexer-rest
            - containerPort: 9300
              name: indexer-nodes
  volumeClaimTemplates:
    - metadata:
        name: wazuh-indexer
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-storage
        resources:
          requests:
            storage: 500Mi
