apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-indexer
  namespace: wazuh
spec:
  serviceName: wazuh-indexer
  replicas: 1

  selector:
    matchLabels:
      app: wazuh-indexer

  template:
    metadata:
      labels:
        app: wazuh-indexer
    spec:
      containers:
        - name: wazuh-indexer
          image: wazuh/wazuh-indexer:4.7.2

          env:
            - name: OPENSEARCH_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
            - name: OPENSEARCH_SECURITY_ENABLED
              value: "false"
            - name: OPENSEARCH_HTTP_SSL_ENABLED
              value: "false"
            - name: OPENSEARCH_TRANSPORT_SSL_ENABLED
              value: "false"
            - name: network.host
              value: "0.0.0.0"
            - name: http.port
              value: "9200"

          ports:
            - containerPort: 9200

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"

          volumeMounts:
            - name: wazuh-indexer-data
              mountPath: /var/lib/wazuh-indexer

      volumes:
        - name: wazuh-indexer-data
          persistentVolumeClaim:
            claimName: wazuh-indexer-pvc
