apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-indexer
  namespace: wazuh
spec:
  serviceName: wazuh-indexer
  replicas: 1

  selector:
    matchLabels:
      app: wazuh-indexer

  template:
    metadata:
      labels:
        app: wazuh-indexer
    spec:
      containers:
        - name: wazuh-indexer
          image: wazuh/wazuh-indexer:4.7.2

          env:
            - name: OPENSEARCH_JAVA_OPTS
              value: "-Xms512m -Xmx512m"

          ports:
            - containerPort: 9200

          volumeMounts:
            - name: wazuh-indexer-data
              mountPath: /var/lib/wazuh-indexer

            # ✅ CORRECT PATH
            - name: indexer-config
              mountPath: /usr/share/wazuh-indexer/opensearch.yml
              subPath: opensearch.yml

      volumes:
        - name: wazuh-indexer-data
          persistentVolumeClaim:
            claimName: wazuh-indexer-pvc

        - name: indexer-config
          configMap:
            name: wazuh-indexer-config
