apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-indexer
  namespace: wazuh
spec:
  template:
    spec:
      containers:
        - name: wazuh-indexer
          env:
            - name: OPENSEARCH_JAVA_OPTS
              value: "-Xms512m -Xmx512m"
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: wazuh-indexer-data
              mountPath: /var/lib/wazuh-indexer
      volumes:
        - name: wazuh-indexer-data
          persistentVolumeClaim:
            claimName: wazuh-indexer-pvc
