apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-indexer-pvc
  namespace: wazuh
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: wazuh-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wazuh-manager-pvc
  namespace: wazuh
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: wazuh-storage
