apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-manager-worker
  namespace: wazuh
spec:
  template:
    spec:
      containers:
        - name: wazuh-manager
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: wazuh-manager-data
              mountPath: /var/ossec/data
      volumes:
        - name: wazuh-manager-data
          persistentVolumeClaim:
            claimName: wazuh-manager-pvc
