apiVersion: v1
kind: Service
metadata:
  name: wazuh-manager
  namespace: wazuh
spec:
  selector:
    app: wazuh-manager-worker
  ports:
    - name: registration
      port: 1515
      targetPort: 1515
    - name: events
      port: 1514
      targetPort: 1514
    - name: api
      port: 55000
      targetPort: 55000
