apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-manager-worker
  namespace: wazuh
spec:
  serviceName: wazuh-manager
  replicas: 1

  selector:
    matchLabels:
      app: wazuh-manager-worker

  template:
    metadata:
      labels:
        app: wazuh-manager-worker
    spec:
      containers:
        - name: wazuh-manager
          image: wazuh/wazuh-manager:4.7.2
          ports:
            - containerPort: 1514
            - containerPort: 1515
            - containerPort: 55000

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"

          volumeMounts:
            - name: wazuh-manager-data
              mountPath: /var/ossec/data

      volumes:
        - name: wazuh-manager-data
          persistentVolumeClaim:
            claimName: wazuh-manager-pvc
