apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-manager-master
  namespace: wazuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-manager
      node-type: master
  serviceName: wazuh-cluster
  template:
    metadata:
      labels:
        app: wazuh-manager
        node-type: master
    spec:
      securityContext:
        fsGroup: 101

      containers:
        - name: wazuh-manager
          image: wazuh/wazuh-manager:4.7.3
          securityContext:
            capabilities:
              add: ["SYS_CHROOT"]
          ports:
            - containerPort: 1515
              name: registration
            - containerPort: 1516
              name: cluster
            - containerPort: 55000
              name: api

          volumeMounts:
            - name: wazuh-manager-storage
              mountPath: /var/ossec/data

          env:
            - name: WAZUH_INDEXER_HOSTS
              value: "wazuh-indexer:9200"
            - name: WAZUH_NODE_NAME
              value: "master"
            - name: WAZUH_NODE_TYPE
              value: "master"
            - name: WAZUH_API_ENABLED
              value: "true"
            - name: WAZUH_API_HOST
              value: "0.0.0.0"
            - name: WAZUH_API_PORT
              value: "55000"
            - name: WAZUH_API_HTTPS
              value: "false"
            - name: API_USERNAME
              valueFrom:
                secretKeyRef:
                  name: wazuh-api-cred
                  key: username
            - name: API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wazuh-api-cred
                  key: password

      volumes:
        - name: wazuh-manager-storage
          persistentVolumeClaim:
            claimName: wazuh-manager-pvc
