apiVersion: v1
kind: Service
metadata:
  name: wazuh-events
  namespace: wazuh
  labels:
    app: wazuh-manager
spec:
  type: LoadBalancer
  selector:
    app: wazuh-manager
    node-type: master
  ports:
    - name: agents-events
      port: 1514
      targetPort: 1514
      protocol: TCP
