apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-manager-master
  namespace: wazuh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wazuh-manager
      node-type: master
  serviceName: wazuh-cluster
  template:
    metadata:
      labels:
        app: wazuh-manager
        node-type: master
    spec:
      securityContext:
        fsGroup: 101
      volumes:
        - name: wazuh-server-certs
          secret:
            secretName: indexer-certs
        - name: wazuh-authd-pass
          secret:
            secretName: wazuh-authd-pass

      containers:
        - name: wazuh-manager
          image: wazuh/wazuh-manager:4.7.3
          resources:
            limits:
              cpu: 400m
              memory: 512Mi
          securityContext:
            capabilities:
              add: ["SYS_CHROOT"]

          volumeMounts:
            - name: wazuh-authd-pass
              mountPath: /wazuh-config-mount/etc/authd.pass
              subPath: authd.pass
              readOnly: true
            - name: wazuh-server-certs
              mountPath: /var/ossec/etc/certs/root-ca.pem
              subPath: root-ca.pem
              readOnly: true
            - name: wazuh-server-certs
              mountPath: /var/ossec/etc/certs/server.pem
              subPath: server.pem
              readOnly: true
            - name: wazuh-server-certs
              mountPath: /var/ossec/etc/certs/server-key.pem
              subPath: server-key.pem
              readOnly: true

          ports:
            - containerPort: 1515
              name: registration
            - containerPort: 1516
              name: cluster
            - containerPort: 55000
              name: api   # 🔴 REQUIRED

          env:
            - name: WAZUH_INDEXER_HOSTS
              value: "wazuh-indexer:9200"
            - name: WAZUH_NODE_NAME
              value: "master"
            - name: WAZUH_NODE_TYPE
              value: "master"
            - name: WAZUH_CLUSTER_BIND_ADDR
              value: "0.0.0.0"
            - name: WAZUH_CLUSTER_NODES
              value: "wazuh-cluster"

            # 🔴 REQUIRED: ENABLE API
            - name: WAZUH_API_ENABLED
              value: "true"
            - name: WAZUH_API_HOST
              value: "0.0.0.0"
            - name: WAZUH_API_PORT
              value: "55000"
            - name: WAZUH_API_HTTPS
              value: "false"

            - name: INDEXER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: indexer-cred
                  key: username
            - name: INDEXER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: indexer-cred
                  key: password

            - name: WAZUH_CLUSTER_KEY
              valueFrom:
                secretKeyRef:
                  name: wazuh-cluster-key
                  key: key
