# Wazuh master Service: API and registration (authd)

apiVersion: v1
kind: Service
metadata:
  name: wazuh-registration
  namespace: wazuh
  labels:
    app: wazuh-manager
spec:
  type: LoadBalancer
  selector:
    app: wazuh-manager
    node-type: master
  ports:
    - name: registration
      port: 1515
      targetPort: 1515
      protocol: TCP
