apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wazuh
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://packages.wazuh.com/helm
    chart: wazuh
    targetRevision: 4.8.1
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/aniketpitre/wazuh-gitops/main/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: wazuh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
