apiVersion: v1
kind: PersistentVolume
metadata:
  name: wazuh-indexer-pv
spec:
  capacity:
    storage: 70Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/wazuh-indexer
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ip-172-31-91-48
