apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wazuh-manager-worker
  namespace: wazuh
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: wazuh-manager
          resources:
            requests:
              memory: "1Gi"
              cpu: "300m"
            limits:
              memory: "1.5Gi"
              cpu: "700m"
