apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wazuh
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/aniketpitre/wazuh-gitops
    targetRevision: main
    path: envs/local-env
    kustomize: {}

  destination:
    server: https://kubernetes.default.svc
    namespace: wazuh

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  ignoreDifferences:
  # 1️⃣ StorageClass (cluster-scoped, mutated)
  - group: storage.k8s.io
    kind: StorageClass
    jsonPointers:
    - /metadata/annotations
    - /provisioner

  # 2️⃣ Secrets (certs -> base64 -> reordered)
  - group: ""
    kind: Secret
    jsonPointers:
    - /data

  # 3️⃣ StatefulSets (PVC templates mutated)
  - group: apps
    kind: StatefulSet
    jsonPointers:
    - /spec/volumeClaimTemplates
