apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wazuh
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/aniketpitre/wazuh-gitops
    targetRevision: main
    path: envs/local-env
    kustomize: {}

  destination:
    server: https://kubernetes.default.svc
    namespace: wazuh

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      
  ignoreDifferences:
  - group: storage.k8s.io
    kind: StorageClass
    jsonPointers:
    - /metadata/annotations
    - /provisioner
